/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface SubcallInterface extends Interface {
  getFunction(
    nameOrSignature: "_parseCBORUint" | "_parseCBORUint128" | "_parseCBORUint64"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "_parseCBORUint",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "_parseCBORUint128",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "_parseCBORUint64",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "_parseCBORUint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_parseCBORUint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_parseCBORUint64",
    data: BytesLike
  ): Result;
}

export interface Subcall extends BaseContract {
  connect(runner?: ContractRunner | null): Subcall;
  waitForDeployment(): Promise<this>;

  interface: SubcallInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  _parseCBORUint: TypedContractMethod<
    [result: BytesLike, offset: BigNumberish],
    [[bigint, bigint] & { newOffset: bigint; value: bigint }],
    "view"
  >;

  _parseCBORUint128: TypedContractMethod<
    [result: BytesLike, offset: BigNumberish],
    [[bigint, bigint] & { newOffset: bigint; value: bigint }],
    "view"
  >;

  _parseCBORUint64: TypedContractMethod<
    [result: BytesLike, offset: BigNumberish],
    [[bigint, bigint] & { newOffset: bigint; value: bigint }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "_parseCBORUint"
  ): TypedContractMethod<
    [result: BytesLike, offset: BigNumberish],
    [[bigint, bigint] & { newOffset: bigint; value: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "_parseCBORUint128"
  ): TypedContractMethod<
    [result: BytesLike, offset: BigNumberish],
    [[bigint, bigint] & { newOffset: bigint; value: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "_parseCBORUint64"
  ): TypedContractMethod<
    [result: BytesLike, offset: BigNumberish],
    [[bigint, bigint] & { newOffset: bigint; value: bigint }],
    "view"
  >;

  filters: {};
}
